### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by jtplaarj** [t-houssian/fillpdf#14]
First of all, thanks for the library. Really helpful.

I think it may be really useful (at least it is for me) a command line interface.

I have done some simple wrappers for your library: [cli_fillpdf](https://github.com/jtplaarj/cli_fillpdf)

If you think is useful, you could add the code to the library, if not, I will keep it public and made if available through pip.

**Comment by t-houssian** [comment]
Great idea and great work! I checked out your repo and think it looks
really good! I would definitely add this into the library code. How would
you like to add the code to the library? I am open to any ideas you have.

Tyler

**Comment by jtplaarj** [comment]
I am very amateur in python and GitHub but I imagine that there are two ways:
- [ ] You could copy and paste into the project.
- [ ] I could clone and do a PR

I suppose that the "correct" GitHub way is the second option. Most likely the first is the simplest.

Any case, you should decide if the command names are OK or you prefer something else. I am quite bad at naming things 😅.

**Comment by t-houssian** [comment]
Do you think you could clone then PR? If you run into issues I could go the copy and paste rout too. I think the names are fitting for now.

**Comment by t-houssian** [comment]
@Thanks, I merged the pull request and documented your functions in the readme file. Let me know if anything is not documented right.

**Comment by jtplaarj** [comment]
i completely forgot the documentation!!! I must admit that you have done a much better job that I would have done.
I have created a PR to fix missing -o option in `extractfillpdf`
#16

**Comment by t-houssian** [comment]
@jtplaarj All good man! Merged it in, thanks for fixing that.
