### ISSUE TITLE
Some pdf versions don't quite work

### ISSUE THREAD

**Issue by tdbs** [t-houssian/fillpdf#4]
I had some pdf (1.4) that didn't work with your code and I made the following changes to your write function to make it work:

```
def write_fillable_pdf_mine(input_pdf_path, output_pdf_path, data_dict):

    ANNOT_KEY = '/Annots'               # key for all annotations within a page
    ANNOT_FIELD_KEY = '/T'              # Name of field. i.e. given ID of field
    ANNOT_FORM_type = '/FT'             # Form type (e.g. text/button)
    ANNOT_FORM_button = '/Btn'          # ID for buttons, i.e. a checkbox
    ANNOT_FORM_text = '/Tx'             # ID for textbox
    SUBTYPE_KEY = '/Subtype'
    WIDGET_SUBTYPE_KEY = '/Widget'
    ANNOT_FIELD_PARENT_KEY = '/Parent'  # Parent key for older pdf versions
    ANNOT_FIELD_KIDS_KEY = '/Kids'      # Kids key for older pdf versions

    template_pdf = pdfrw.PdfReader(input_pdf_path)
    for Page in template_pdf.pages:
        if Page[ANNOT_KEY]:
            for annotation in Page[ANNOT_KEY]:
                target = annotation if annotation[ANNOT_FIELD_KEY] else annotation[ANNOT_FIELD_PARENT_KEY]
                if target and annotation[SUBTYPE_KEY] == WIDGET_SUBTYPE_KEY:
                    key = target[ANNOT_FIELD_KEY][1:-1] # Remove parentheses
                    if key in data_dict.keys():
                        if target[ANNOT_FORM_type] == ANNOT_FORM_button:
                            # button field i.e. a checkbox
                            target.update( pdfrw.PdfDict( V=pdfrw.PdfName(data_dict[key]) , AS=pdfrw.PdfName(data_dict[key]) ))
                            if target[ANNOT_FIELD_KIDS_KEY]:
                                target[ANNOT_FIELD_KIDS_KEY][0].update( pdfrw.PdfDict( V=pdfrw.PdfName(data_dict[key]) , AS=pdfrw.PdfName(data_dict[key]) ))
                        elif target[ANNOT_FORM_type] == ANNOT_FORM_text:
                            # regular text field
                            target.update( pdfrw.PdfDict( V=data_dict[key], AP=data_dict[key]) )
                            if target[ANNOT_FIELD_KIDS_KEY]:
                                target[ANNOT_FIELD_KIDS_KEY][0].update( pdfrw.PdfDict( V=data_dict[key], AP=data_dict[key]) )
    template_pdf.Root.AcroForm.update(pdfrw.PdfDict(NeedAppearances=pdfrw.PdfObject('true')))
    pdfrw.PdfWriter().write(output_pdf_path, template_pdf)
```

**Comment by tdbs** [comment]
It seems some files have a Parent and Kids keys inside the annotations, this change made it compatible with the new and old files, although i'm not sure about that ```target[ANNOT_FIELD_KIDS_KEY][0].update```, in my cases the Kids always only had one element, but you can probably figure it out

**Comment by Micboule** [comment]
> I had some pdf (1.4) that didn't work with your code and I made the following changes to your write function to make it work:
> 
> ```
> def write_fillable_pdf_mine(input_pdf_path, output_pdf_path, data_dict):
> 
>     ANNOT_KEY = '/Annots'               # key for all annotations within a page
>     ANNOT_FIELD_KEY = '/T'              # Name of field. i.e. given ID of field
>     ANNOT_FORM_type = '/FT'             # Form type (e.g. text/button)
>     ANNOT_FORM_button = '/Btn'          # ID for buttons, i.e. a checkbox
>     ANNOT_FORM_text = '/Tx'             # ID for textbox
>     SUBTYPE_KEY = '/Subtype'
>     WIDGET_SUBTYPE_KEY = '/Widget'
>     ANNOT_FIELD_PARENT_KEY = '/Parent'  # Parent key for older pdf versions
>     ANNOT_FIELD_KIDS_KEY = '/Kids'      # Kids key for older pdf versions
> 
>     template_pdf = pdfrw.PdfReader(input_pdf_path)
>     for Page in template_pdf.pages:
>         if Page[ANNOT_KEY]:
>             for annotation in Page[ANNOT_KEY]:
>                 target = annotation if annotation[ANNOT_FIELD_KEY] else annotation[ANNOT_FIELD_PARENT_KEY]
>                 if target and annotation[SUBTYPE_KEY] == WIDGET_SUBTYPE_KEY:
>                     key = target[ANNOT_FIELD_KEY][1:-1] # Remove parentheses
>                     if key in data_dict.keys():
>                         if target[ANNOT_FORM_type] == ANNOT_FORM_button:
>                             # button field i.e. a checkbox
>                             target.update( pdfrw.PdfDict( V=pdfrw.PdfName(data_dict[key]) , AS=pdfrw.PdfName(data_dict[key]) ))
>                             if target[ANNOT_FIELD_KIDS_KEY]:
>                                 target[ANNOT_FIELD_KIDS_KEY][0].update( pdfrw.PdfDict( V=pdfrw.PdfName(data_dict[key]) , AS=pdfrw.PdfName(data_dict[key]) ))
>                         elif target[ANNOT_FORM_type] == ANNOT_FORM_text:
>                             # regular text field
>                             target.update( pdfrw.PdfDict( V=data_dict[key], AP=data_dict[key]) )
>                             if target[ANNOT_FIELD_KIDS_KEY]:
>                                 target[ANNOT_FIELD_KIDS_KEY][0].update( pdfrw.PdfDict( V=data_dict[key], AP=data_dict[key]) )
>     template_pdf.Root.AcroForm.update(pdfrw.PdfDict(NeedAppearances=pdfrw.PdfObject('true')))
>     pdfrw.PdfWriter().write(output_pdf_path, template_pdf)
> ```

Wow, you solved my problem, the same field name in the PDF that was repeating on multiple pages wasn't filling the field at all. 

Now, it does! Fantastic! 👍 

Thank you!
