### ISSUE TITLE
Sanitize dictionary inputs

### ISSUE THREAD

**Issue by stevobailey** [t-houssian/fillpdf#5]
It didn't work for me when my dictionary contained floats instead of strings:

```
values_dict = {'field': 7.2}
fillpdfs.write_fillable_pdf(input_filename, output_filename, values_dict)
```

But if I just wrap all dictionary values in a `str()` call then it works.

**Comment by patrick-osborne** [comment]
Had the same issue with the same solution - casting to string solves the problem nicely.

**Comment by t-houssian** [comment]
@stevobailey @patrick-osborne Thanks for the input, I added this to the code.
